image: spittet/node-mysql

pipelines:
  default:
    - step:
        script:
          - /etc/init.d/mysql start
          - mysql -u root -e 'CREATE DATABASE test'
          - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' =  PASSWORD('test')"
          - rm -rf node_modules
          - npm install --silent
          - npm test --silent
  branches:
    master:
      - step:
          image: edgecase/docker-ubuntu-node-awscli
          script:
            - npm install -g n && n 4.2.0 && node -v
            - apt-get install -y zip
            - npm run deploy