image: edgecase/docker-ubuntu-node-awscli

pipelines:
  default:
    image
    - step:
      script:
        - npm install
        - npm run integration-tests
  branches:
    master:
      - step:
          script:
            - npm install -g n && n 4.2.0 && node -v
            - apt-get install -y zip
            - npm run deploy